frontend/controllers/CcbController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\Cookie;
use common\models\customer\Customer;
use yii\web\NotFoundHttpException;
use common\models\plan\Plan;
use common\models\saleable\Saleable;
use backend\utilities\helpers\Mail;
use yii\helpers\Url;
use frontend\models\QuantityForm;
use common\models\inventory\Inventory;
use frontend\models\PaymentTypeForm;
use yii\helpers\ArrayHelper;
use common\models\order\Order;
use common\models\order\detail\OrderDetail;
use backend\utilities\helpers\ClientHelper;
use common\models\payments\Cybersource;
use common\models\payment\Payment;
use Swift_TransportException;
use backend\utilities\helpers\TimeHelper;

/**
 * Site controller
 */
class CcbController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action) {
        

        if (Yii::$app->request->isGet && Yii::$app->controller->action->id != 'error' && Yii::$app->controller->action->id != 'info' && false) {
            $customer_hash_code = Yii::$app->request->get('code', '');
            $event_link = Yii::$app->request->get('event', '');
            $saleable_link = Yii::$app->request->get('type', '');

            if (empty($event_link) || empty($saleable_link)) {
                throw new NotFoundHttpException('Please check your link');
            }

            if (empty($customer_hash_code)) {
                if (Yii::$app->controller->action->id != 'index') {
                    throw new NotFoundHttpException('Please check your link');
                }
            } else {

                $inventory_ids = Yii::$app->session->get($customer_hash_code . '_inventory_ids', []);
                $quantity_form = Yii::$app->session->get($customer_hash_code . '_form', '');

                $start_time = Yii::$app->session->get($customer_hash_code . '_start_time', '');
                if ((Yii::$app->controller->action->id == 'confirm-order' && empty($inventory_ids) && empty($quantity_form)) || (Yii::$app->controller->action->id != 'success' && !empty($start_time) && $start_time < strtotime("-60 minutes"))) {

                    Inventory::updateAll([
                        'status' => Inventory::STATUS_AVAILABLE
                            ], ['id' => $inventory_ids, 'status' => Inventory::STATUS_PROCESSING]);

                    Yii::$app->session->removeAll();
                    Yii::$app->session->setFlash('message', 'Your session is expired');
                    return $this->redirect(['index', 'event' => $event_link, 'type' => $saleable_link]);
                }
            }
        }
        return parent::beforeAction($action);
    }

    public function init() {
        parent::init();
        $cookies = Yii::$app->request->cookies;
        $language = $cookies->getValue('language', 'vi');
        Yii::$app->language = $language;
    }

    public function actionChangeLang() {
        $lang = Yii::$app->request->post('lang', ''); //en
        // Yii::$app->language = $lang;
        $cookie = new Cookie([
            'name' => 'language',
            'value' => $lang
        ]);
        \Yii::$app->getResponse()->getCookies()->add($cookie);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex() {
        $event_link = Yii::$app->request->get('event', '');
        $saleable_link = Yii::$app->request->get('type', '');
        $plan = Plan::find()->where(['link' => $event_link])->isRunning()->one();
        $saleable = Saleable::find()->where(['link' => $saleable_link])->active()->one();
        $customer = new Customer();
        if (isset($plan) && isset($saleable) && isset($saleable->plan) && $saleable->plan->hash_code == $plan->hash_code) {
            if (Yii::$app->request->isPost) {
                //Customer[reCaptcha]
                //if($customer->getr)
                $email = Yii::$app->request->post('Customer')['email'];
                $email = Yii::$app->request->post('Customer')['email'];
                $old_customer = Customer::find()->where(['email' => trim($email)])->one();

                if (isset($old_customer)) {
                    $customer = $old_customer;
                }

                $customer->hash_code = Yii::$app->getSecurity()->generateRandomString(24);
                $customer->otp_date = time();
                $customer->is_verified = 0;
                $customer->verified_date = null;

                if ($customer->load(Yii::$app->request->post()) && $customer->save()) {
                    Yii::$app->session->set('customer_id', $customer->id);
                    /**
                     * I have wrote this but the client said they do not want customer to have too much steps before they can buy something, please confirm before you un-comment this
                    $mail = new Mail([
                        'subject' => $plan->name,
                        'mailTo' => $customer->email,
                        'content' => ''
                    ]);
                    try {
                        $mail->send(['html' => 'otp-confirm'], [
                            'customerName' => $customer->fullname,
                            'otp' => Url::to('/ccb/confirm?code=' . $customer->hash_code . '&event=' . $event_link . '&type=' . $saleable_link, true)
                        ]);
                    } catch (Swift_TransportException $e) {
                        throw new NotFoundHttpException('Our server is busing at the moment, please come back later.');
                    }
                    return $this->redirect(['ccb/info', 'event' => $event_link, 'type' => $saleable_link]);
                     * 
                     */
                    return $this->redirect(Url::to('/ccb/confirm?code=' . $customer->hash_code . '&event=' . $event_link . '&type=' . $saleable_link, true));
                }
            }
            Yii::trace($customer->getErrors());
            return $this->render('index', [
                        'customer' => $customer,
                        'name' => $saleable->{'name_' . Yii::$app->language}
            ]);
        }
        throw new NotFoundHttpException('Please check your link');
    }

    public function actionInfo() {
        $customer_id = Yii::$app->session->get('customer_id', '');
        $customer = Customer::findOne(['id' => $customer_id]);
        if (isset($customer)) {
            return $this->render('about', [
                        'customer' => $customer
            ]);
        }
        throw new NotFoundHttpException('Please check your link');
    }

    public function actionConfirm() {
        $customer_hash_code = Yii::$app->request->get('code', '');
        $event_link = Yii::$app->request->get('event', '');
        $saleable_link = Yii::$app->request->get('type', '');


        $plan = Plan::find()->where(['link' => $event_link])->isRunning()->one();
        $saleable = Saleable::find()->where(['link' => $saleable_link])->active()->one();
        $customer = Customer::find()->where(['hash_code' => trim($customer_hash_code)])->one();

        if (!(isset($customer) && isset($plan) && isset($saleable) && $saleable->plan->hash_code == $plan->hash_code)) {
            throw new NotFoundHttpException('Please check your link');
        }

        $time = ($customer->is_verified == 1) ? true : $customer->otp_date + 3600 > time();
        if ($time) {

            Yii::$app->session->set($customer_hash_code . 'plan_hash_code', $plan->hash_code);
            Yii::$app->session->set($customer_hash_code . 'saleable_hash_code', $saleable->hash_code);

            $customer->updateAttributes([
                'is_verified' => 1,
                'verified_date' => time(),
                    //'hash_code' => Yii::$app->getSecurity()->generateRandomString(24)
            ]);

            return $this->redirect(['book', 'code' => $customer_hash_code, 'event' => $event_link, 'type' => $saleable_link]);
        }
        return $this->render('expired', [
                    'customer' => $customer
        ]);
    }

    public function actionBook() {
        $customer_hash_code = Yii::$app->request->get('code', '');
        $event_link = Yii::$app->request->get('event', '');
        $saleable_link = Yii::$app->request->get('type', '');
        $customer = Customer::find()->where(['hash_code' => trim($customer_hash_code)])->one();

        $quantityForm = new QuantityForm();

        $plan = Plan::find()->where(['link' => $event_link])->isRunning()->one();
        $saleable = Saleable::find()->where(['link' => $saleable_link])->active()->one();

        if (!(isset($customer) && isset($plan) && isset($saleable) && $saleable->plan->hash_code == $plan->hash_code)) {
            throw new NotFoundHttpException('Please check your link');
        }
        
        if($saleable->is_dynamic_checkout){
            $quantityForm->setScenario(QuantityForm::SCR_DYNAMIC_CHECKOUT);
        }
        
        //$ids = Yii::$app->session->get($customer_hash_code . '_inventory_ids', []);
        //Inventory::updateAll(['status' => Inventory::STATUS_AVAILABLE], ['id' => $ids, 'status' => Inventory::STATUS_PROCESSING, 'customer_id' => $customer->id]);
        Yii::$app->session->set($customer_hash_code . '_inventory_ids', []);

frontend/views/layouts/cocobus.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;
use yii\helpers\Url;

//AppAsset::register($this);
$language    = 'vi';

// get a session variable. The following usages are equivalent:
if (isset(Yii::$app->request->cookies['language']->value)) {
    $language = Yii::$app->request->cookies['language']->value;
}
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en-us">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--[if IE]><meta http-equiv="x-ua-compatible" content="IE=9" /><![endif]-->
  <title>Cocobus</title>
  <link rel="shortcut icon" href="img/favicon.ico">

  <!-- GOOGLE FONTS-->
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">

  <!-- STYLESHEETS-->
  <link href="/styles/cocobus/css/bootstrap.min.css" rel="stylesheet">
  <link href="/styles/cocobus/css/font-awesome.min.css" rel="stylesheet">
  <link href='/styles/cocobus/css/owl.carousel.css' rel="stylesheet">
  <link href='/styles/cocobus/css/style.css' rel="stylesheet">
  <link href='/styles/cocobus/css/responsive.css' rel="stylesheet"> 
  <link rel="stylesheet" href="/styles/cocobus/css/animate.css">
  <link rel="stylesheet" href="/styles/cocobus/css/feast.css">
  <link rel="stylesheet" href="/styles/cocobus/css/cocobos.css">
  <script src="/styles/cocobus/js/jquery-1.9.1.min.js" type="text/javascript"></script> <script>
  ;(function() {
    'use strict';


    $(activate);


    function activate() {

      $('.nav-tabs').scrollingTabs();

    }
  }());
</script>

    <!--[if lte IE 9]>
      <script src="js/respond.min.js" type="text/javascript"></script>
      <![endif]-->
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    </head>
    <body class="enable-fixed-header">
<?php $this->beginBody() ?>
    <!-- Start Header -->
    <header id="header" class="triangle">

      <!-- Start Banner -->
      <div id="banner">
        <div class="banner-bg">
          <div class="banner-bg-item"><img src="/styles/cocobus/img/cocobay/CocoBusBanner.jpg" alt=""></div>
        </div>

        <!-- Start Header-Inner -->
        <div class="header-inner cleafix">
          <!-- Start Header-Logo -->
          <div class="header-logo">
            <a href="https://www.cocobay.vn">
              <img  style="margin-top: 60px;"  src="/styles/cocobus/img/cocobay/logo-1.png" alt="logo" class="toplogo">
            </a>
          </div>
          <!-- End Header-Logo -->
          <!-- Start Header-Tool-Bar -->
          <div class="header-tool-bar tops">
            <div class="container">
              <div class="row">

                <!-- Start Header-Left -->
                <div class="col-lg-4 col-md-5 col-xs-12 header-left">

                  <!-- Start Header-Contact -->
                  <ul class="custom-list header-contact">
                    <li>
                      <i class="yellow-nav">Hotline</i>
                      +84 23 6395 4666
                    </li>
                    <li>
                      <i  class="yellow-nav" style="padding-left: 25px;">Follow us</i>
                      
                      <ul class="header-social custom-list">
                        <li class="social-mobi"><a href="https://www.facebook.com/CocobayOfficial/" target="_blank"><i class="fa fa-facebook-square"></i></a></li>
                        <li class="social-mobi"><a href="https://www.youtube.com/channel/UCxjGy9lqQnHSyd50lVjsFCw" target="_blank"><i class="fa fa-youtube-play"></i></a></li>
                        <li class="social-mobi"><a href="https://www.instagram.com/cocobayofficial/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                      </ul> 
                    </li>
                  </ul>
                  <!-- End Header-Contact -->

                </div>
                <!-- End Header-Left -->

                <!-- Start Header-Right -->
                <div class="col-lg-4 col-md-5 col-sm-12 col-xs-12 col-lg-offset-4 col-md-offset-2 header-right">

                  <ul class="custom-list header-contact">
                    <!-- Start Header-Language -->
                    <li><div class="header-language">
                      <button class="header-btn">
                        <i class="fa fa-globe"></i>
                        EN
                      </button>
                      <nav class="header-form">
                        <ul class="custom-list">
                          <li class="active"><a href="#">VI</a></li>
                        </ul>
                      </nav>
                    </div></li></ul>
                    <!-- End Header-Language -->

                  </div>
                  <!-- End Header-Right -->

                </div>
              </div>
            </div>
            <!-- End Header-tool-bar -->

            <!-- Start Header-Nav -->
            <div class="header-nav">
            </div>
            <!-- End Header-Nav -->

          </div>
          <!-- End Header-Inner -->

          <div class="css-table">
            <div class="css-table-cell cell-search">
            </div>
          </div>

        </div>
        <!-- End Banner -->

      </header>
      <!-- End Header -->

      <!-- Our stay4 -->
      <section class="feast2">
        <div class="container-fluid">
          <div class="row">
            <!-- Start stay4 -->
            <div class="col-sm-12 bg-stay4 ">
              <img src="/styles/cocobus/img/cocobay/ccb-feast2/restaurant.png"/ class="wow fadeInDown" style="padding-top:60px;">
              <h1 class="title wow fadeInDown"><span style="background: -webkit-linear-gradient(#673AB7, #e91e63de);-webkit-background-clip: text;-webkit-text-fill-color: transparent;">COCO BUS</span> <span style="background: -webkit-linear-gradient(#673AB7, #e91e63de);-webkit-background-clip: text;-webkit-text-fill-color: transparent;">TOUR</span></h1>
              <img class="below-p wow fadeInDown" src="/styles/cocobus/img/cocobay/gach-title.PNG"/>
            </div>
          </div>
        </div>
      </section>

      <!-- Start Banner -->

      <div>
       <div id="my-popup" style="margin-top: 0;" class="wow slideInDown" data-wow-duration="2s">
        <div class="row">
         <div class="col-sm-12" style="text-align: center;">
          <h3 class="title-projects">BOOK BUS</h3>
          <p class="sub-titlte-projects">Please fill your information into fields below</p>
          <img class="below-h1" src="/styles/cocobus/img/cocobay/gach-title-white.png"/>
        </div>
		<?= $content ?>
    </div>
  </div>
</form>
</div>
</div>
<!-- End Banner -->



  <!-- Start Footer -->
  <footer id="footer">
          <!-- Start Footer-Menu -->
          <div class="footer-copyrights">
            <div class="container">
              <div class="row">
                <div class="col-lg-12">
                  <a href="#" class="link-footer">About Empire Group</a> | <a href="#" class="link-footer">Privacy Policy</a> | <a href="#" class="link-footer">Terms Of Use</a> | <a href="#" class="link-footer">Terms & Conditions</a>
                </div>
              </div>
            </div>
          </div>
          <!-- End Footer-Menu -->

        </footer>
        <!-- End Footer -->

        <a href="#" class="btn" id="back-to-top"><i class="fa fa-arrow-up"></i></a>

        <!-- SCRIPTS-->
        <script src="/styles/cocobus/js/jquery-1.9.1.min.js" type="text/javascript"></script><script src="/styles/cocobus/js/slick.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="/styles/cocobus/js/bootstrap.min.js"></script>
        <script src="/styles/cocobus/js/owl.carousel.min.js"></script>
        <script src="/styles/cocobus/js/jquery.vide.min.js"></script>
        <script src="/styles/cocobus/js/jquery-ui-1.10.4.custom.min.js"></script>
        <script src="/styles/cocobus/js/script.js"></script>
        <script src="/styles/cocobus/js/jquery.ba-outside-events.min.js"></script>
        <script src="/styles/cocobus/js/jquery.magnific-popup.min.js"></script>
        <script src="/styles/cocobus/js/jquery.placeholder.js"></script>
        <script type="text/javascript" src="/styles/cocobus/js/jquery.flexisel.js"></script>

        <script type="text/javascript" src="/styles/cocobus/js/scroll.js"></script>
        <script src="/styles/cocobus/js/wow.js"></script>
        <script>
          wow = new WOW(
          {
            animateClass: 'animated',
            offset:       100,
            callback:     function(box) {
              console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")
            }
          }
          );
          wow.init();
        </script> <script>$("#open-popup").magnificPopup({type:"inline",callbacks:{open:function(){$.magnificPopup.instance.close=function(){confirm("Are you sure?")&&$.magnificPopup.proto.close.call(this)}}}});</script>
		<script>$("#open-popup1").magnificPopup({type:"inline",callbacks:{open:function(){$.magnificPopup.instance.close=function(){confirm("Are you sure?")&&$.magnificPopup.proto.close.call(this)}}}});</script>
        <script>var nav=$("div.header-tool-bar.tops");$(window).scroll(function(){$(window).scrollTop()>50?nav.removeClass("tops"):nav.addClass("tops")});var nav1=$("img.toplogo");$(window).scroll(function(){$(window).scrollTop()>50?nav1.removeClass("toplogo"):nav1.addClass("toplogo martop")});</script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;
use yii\helpers\Url;

AppAsset::register($this);
$language    = 'vi';

// get a session variable. The following usages are equivalent:
if (isset(Yii::$app->request->cookies['language']->value)) {
    $language = Yii::$app->request->cookies['language']->value;
}

$this->registerJs('if($("#lang").val() == "vi"){$("#vi").attr("class","active");}else{$("#en").attr("class","active");}$("body").on("click", ".lang", function () {$.ajax({method: "POST",url: "'. Url::to(['ccb/change-lang']) . '",data: {lang:$(this).data("lang")}}).done(function (result) {location.reload();});})');

$background_src = Url::to('@web/images/bg.png');

$this->registerCss('.bg-cover{background: url('. $background_src .') no-repeat center center fixed; -webkit-background-size: cover;  -moz-background-size: cover;  -o-background-size: cover;  background-size: cover;}');

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109838388-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-109838388-2');
    </script>

    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<input type="hidden" id="lang" value="<?= $language ?>">
<div class="wrap bg-cover">
    <?php
    NavBar::begin([
        'brandLabel' => Html::img('@web/images/logo.png', ['alt' => 'My logo']),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        '<li id="vi"><a href="javascript:void(0);" class="lang" data-lang="vi" >VI</a></li>',
        '<li id="en"><a href="javascript:void(0);" class="lang" data-lang="en" >EN</a></li>'
    ];
echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>